name: rabbitmq

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data:/var/lib/rabbitmq
      # If you want to use third party plugins(like rabbitmq_delayed_message_exchange), please follow the steps below:
      #   1. comment below lines and docker-compose up once
      #   2. docker cp rabbitmq:/opt/rabbitmq/plugins ./plugins && docker cp rabbitmq:/etc/rabbitmq/enabled_plugins ./enabled_plugins
      #   3. then put third party plugins in the plugins folder
      #   4. update the enabled_plugins file to include the third party plugins
      - ./plugins:/opt/rabbitmq/plugins
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins