name: mysql

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql

  adminer:
    image: adminer:4-standalone
    restart: always
    ports:
      - 3307:8080
